### ISSUE TITLE
Regarding colorscheme highlights breaking in some cases (headlines.nvim specifically)

### ISSUE THREAD

**Issue by megalithic** [lukas-reineke/virt-column.nvim#25]
https://github.com/lukas-reineke/virt-column.nvim/blob/29db24c5e94243df1f34f47bbcb4e7803204cae4/lua/virt-column/init.lua#L26

@lukas-reineke I've narrowed my issue down (mentioned here https://github.com/lukas-reineke/virt-column.nvim/issues/18) to clearing the ColorColumn highlight. To get around this, I'm simply adding it back in the markdown ftplugin. Not optimal, but at least "fixes" it for now. 

Ironically, this clearing of ColorColumn breaks headlines.nvim (https://github.com/lukas-reineke/headlines.nvim/blob/master/lua/headlines/init.lua#L78-L79).

**Comment by lukas-reineke** [comment]
I see, I totally misunderstood your problem, sorry.

To use virt-column.nvim you have to clear `ColorColumn`, otherwise it will not look right. And highlight groups are global, you can't turn them back on only for markdown. If you add it back in the markdown ftplugin, it just means you will turn them back on globally once you edit one markdown file.

In cases like headlines.nvim, where there are highlight groups that default link to `ColorColumn`, you have to define those highlight groups directly instead.
So the correct fix for headlines.nvim is not to add back `ColorColumn`, but to define `Headline` and `CodeBlock` highlight groups.
